### PR TITLE
Make reactCellRendererFactory work with React Router

### LINKED ISSUE #18: reactCellRendererFactory does not work with react-redux, or react-router
Since the `reactCellRendererFactory` is creating new react contexts for each cell, using react router components like `Link` (or anything else that relies on React-Redux's `context`) will not work.  Props get passed down like normal, but context is used heavily by react-router and redux.  Any idea on how to support this?

### PR DESCRIPTION
**Pull request by sjmatta**
This resolves #18 and preserves backwards compatibility.

If you send the optional second parameter to reactCellRendererFactory to supply a parentComponent, that parentComponent's context will be preserved in the newly rendered subtree.

### CODE REVIEW

File: src/ReactCellRendererFactory.ts [hunk 1]
```diff
@@ -1,13 +1,17 @@
 var React = require('react');
 var ReactDOM = require('react-dom');
 
-export function reactCellRendererFactory(reactComponent: any): ( (params: any) => HTMLElement | string) {
+export function reactCellRendererFactory(reactComponent: any, parentComponent?: any): ( (params: any) => HTMLElement | string) {
```
Comment (sjmatta) [inline src/ReactCellRendererFactory.ts]: I don't use TypeScript on a regular basis, so I'm not sure if there's a more appropriate type for parentComponent than "any".

**Comment by ceolter** [comment]
i'll put this in manually, as you checked in the js files!! (these are  generated).

however, can you advise, what's your confidence that this is the right solution?

it looks pretty safe, as it's backward compatible.

also, can you advise, what the instructions are for usage? is it enough to say 'pass in the parent component as the second paramter'? or does the parent component have to be something more specific?

also, what other things would this be fixing?

sorry if the above are basic questions, i'm not claiming to be a React expert!

**Comment by sjmatta** [comment]
I got rid of changes to the generated files - sorry, wasn't sure what your checkin style was!

I did some research before providing this solution by looking at how others have approached it. This is a pretty common solution. There's a risk the API might change in future versions of React, but for now, it's the only function they have to resolve this particular use case. I'm hoping @jameswyse or @DanielNesbitt can chime in?

The `parentComponent` needs to be the React component you want to inherit context from. Users can think of it as virtually attaching the reactComponent as a child to the parentComponent.

I don't think this fixes anything else - it should be limited to just allowing parentComponent's context to work on the child component. For me, this means I can use React Router in the child component. :tada:

**Comment by ceolter** [comment]
i think it may also fix some performance issues people are experiencing with React cellRenders.

i wonder if we can have it so it uses the ag-Grid component as the parent component???

**Comment by ceolter** [comment]
i plan merging this pretty soon btw

**Comment by sjmatta** [comment]
@ceolter Thanks! I'll look into your questions.

**Comment by gabrielenosso** [comment]
I think that one best way to optimize performance would be to use a default external root component if the parentComponent is not specified.
If it specified, then the PR code will work fine (and it will also pass the context).

Is it possible to achieve?

**Comment by gabrielenosso** [comment]
@sjmatta Could you also provide some examples about how to use it in the best way?
It could be helpful for the documentation :)

**Comment by ceolter** [comment]
i've updated the ag-grid-example to use this

i also create another example with lots of rows and columns, all using React cellRenderer.

i was hoping to use my new example to troubleshoot the performance issue people are telling me about in React, however it works just as fast as the non-React version (ie very fast).

**Comment by vidhib** [comment]
@sjmatta :  I'd really appreciate your help! I have tried quite a bit but can't figure out how to use react-router as the second parameter in this custom cell renderer. I have a cell render which I'd like to be a router component so that clicking on it will take me to another page.

The hierarchy is very simple in my application. At a certain point in the application path, I show a page that contains the ag-grid. This page has reference to router.

Here's a little bit code..
Here's my cell renderer:   cellRenderer: reactCellRendererFactory(DomainCellRenderer, this) 

 I am expecting the function changeFocus to have router related information available as this.props.
My CellRenderer code is shown below:
  render(){
    return(
      <div>
        <a href="#" onClick={this.changeFocus}>
          {this.props.value}
        </a>
      </div>
    )
  }

I also tried to wrap my cell renderer withRouter function to get reference to the router but I think I'm doing something terribly wrong.

Would be very thankful for your help!!

**Comment by sjmatta** [comment]
I think it stopped working in the newest major version. I'll see if I can adapt the fix.

**Comment by Jmac1523** [comment]
Hi all, 

Circling back here after following the link to this PR in the file's comments. I'm using the factory to render a column of html checkboxes in each row. I need to disable all checkboxes that don't match the a row value of the selected checkbox. To for the re-render, we added  
`if (params !== void 0) {
      setTimeout(() => {
        renderCell(params, params.eParentOfValue.element);
      }, 10);
    }` 
and are using `this.api.softRefreshView` on the checkbox selection. It works as intended, however I'm getting `Uncaught TypeError: Cannot read property '__reactInternalInstance$9npyqh1jt61xnahk5znlmobt9' of null` when it goes to call the `renderCell` function in the `setTimeout`. Would anyone have an idea as to what might be causing this/a possible change or workaround? I can provide more detail/source code if needs be. Thanks in advance!
